name: 🚀 GHCR & Docker Hub Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - Dockerfile
      - .github/workflows/publish.yml
      - README.md
  workflow_dispatch:

jobs:
  publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: production  # 🔐 Required to access environment-level secrets

    permissions:
      contents: read
      packages: write

    steps:
      - name: 📥 Checkout source
        uses: actions/checkout@v4

      - name: 🕵️ Inspect Trigger Context
        run: |
          echo "Triggered by ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"
          echo "Event name: ${{ github.event_name }}"

      - name: 🧼 Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: KitQuietDev
          password: ${{ secrets.GHCR_PAT }}

      - name: 🔐 Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: 🛠️ Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/kitquietdev/rmeta:latest
            ghcr.io/kitquietdev/rmeta:${{ github.ref_name }}
            kitquietdev/rmeta:latest
            kitquietdev/rmeta:${{ github.ref_name }}
          build-args: |
            ENV=production
            VERSION=${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true
